const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('companion', {
  getSvg: () => ipcRenderer.invoke('get-svg'),
  getStats: () => ipcRenderer.invoke('get-stats'),
  onStats: (cb) => ipcRenderer.on('stats', (_e, stats) => cb(stats)),
  onHands: (cb) => ipcRenderer.on('hands', (_e, hands) => cb(hands)),
  onAvatarChanged: (cb) => ipcRenderer.on('avatar-changed', () => cb()),
  setIgnoreMouse: (ignore) => ipcRenderer.send('set-ignore', ignore),
  scaleBy: (factor) => ipcRenderer.send('scale-by', factor),
  dragStart: () => ipcRenderer.send('drag-start'),
  dragEnd: () => ipcRenderer.send('drag-end'),
  contextMenu: () => ipcRenderer.send('context-menu'),
  resetStats: () => ipcRenderer.send('reset-stats'),
  hide: () => ipcRenderer.send('hide'),
  donate: () => ipcRenderer.send('donate'),
  quit: () => ipcRenderer.send('quit'),
  getProgress: () => ipcRenderer.invoke('get-progress'),
  onProgress: (cb) => ipcRenderer.on('progress', (_e, p) => cb(p)),
  onUnlocked: (cb) => ipcRenderer.on('unlocked', (_e, info) => cb(info)),
  setAvatar: (id) => ipcRenderer.send('set-avatar', id),
  getApps: () => ipcRenderer.invoke('get-apps'),
  onApps: (cb) => ipcRenderer.on('apps', (_e, apps) => cb(apps)),
  openTracker: () => ipcRenderer.send('open-tracker'),
  getTrackerList: () => ipcRenderer.invoke('get-tracker-list'),
  setAppTracked: (exe, tracked) => ipcRenderer.send('set-app-tracked', exe, tracked),
  setAllTracked: (tracked) => ipcRenderer.send('set-all-tracked', tracked),
  setAutoTrack: (on) => ipcRenderer.send('set-auto-track', on),
});
